env:
  global:
    - secure: vpb8bouCdr1JyG2pRncbwjqh5NIAbShq9DWxS2LmdqBh0c4/BIZNpjUoifwr10zZFHb6134dTnFvcfHS8rARGODUijrvUzN4pt1zHYku2VNI/70xmI/tiqZc17RIyEFNZypfeogug8cs47Vck5u0ce32vsfYLMk/Uqn7oy3tMzAp/Rkg54hlbaersRo7YBxqrcoJrNiMi9Ri7L3qVgQd01WZQgGHT/M2ffV6bg7QgAZg2ZimQz0Ila3qjLnB07c3dv0iIDvXO5bQCcNfI7Rh3qGtjeXmrWMLSn12CanBEzE1FmgCk86/SasFx/P6nZScHvfj2ilNv8T5M0kl2UMdANIbgpdKD5Ft+1NGUR+bSxdv1o+NEhIHpKwPECMpQ5zKucTIC5MThFt2k4o7U2472eentSNPmPyN6J47eTxfqL8g1TR4ZnICL5cIzipASgsk3/HTaNSWPHJs7sRmGltMTorbp/hkcmZ6LrT+Vqy0RvWKzxeS4aaTUZ9X973DLKOorgBF78tEj6Upqm3u0q1A6ZsBuOygxVLxdqic5rDP51Ay+f+erFR1H42IOZeZKE/RCzmCDnAkaPWeXVhnJklLreSqB0ll+c3mg/47f1Hv1r0DLUhEUpeaJAILFK3R8ZBF12mrlj8QI6WBKJXWYDEsMCvyPgosp23INnWdNIUMTBw=
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-26
          - android-24
          - sys-img-armeabi-v7a-android-24
      before_script:
        - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a -c 100M
        - emulator -avd test -no-window &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
        - echo ", ':safe-app-android'" >> settings.gradle
        - ./gradlew :safe-app-android:download-nativelibs
      before_deploy:
        - ./gradlew :safe-app-android:javadoc
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_ACCESS_TOKEN
        local_dir: safe-app-android/build/docs/javadoc
        on:
          branch: master
    - os: osx
      language: java
      osx_image: xcode10.1
  allow_failures:
    - os: osx
before_install:
  - chmod +x gradlew
script:
  - ./gradlew download-nativelibs
  - ./gradlew check
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew :safe-app-android:runInstrumentationTests; fi

