language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/android-sdk-dl
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
env:
  global:
    - ANDROID_HOME=$HOME/.android
    - secure: vpb8bouCdr1JyG2pRncbwjqh5NIAbShq9DWxS2LmdqBh0c4/BIZNpjUoifwr10zZFHb6134dTnFvcfHS8rARGODUijrvUzN4pt1zHYku2VNI/70xmI/tiqZc17RIyEFNZypfeogug8cs47Vck5u0ce32vsfYLMk/Uqn7oy3tMzAp/Rkg54hlbaersRo7YBxqrcoJrNiMi9Ri7L3qVgQd01WZQgGHT/M2ffV6bg7QgAZg2ZimQz0Ila3qjLnB07c3dv0iIDvXO5bQCcNfI7Rh3qGtjeXmrWMLSn12CanBEzE1FmgCk86/SasFx/P6nZScHvfj2ilNv8T5M0kl2UMdANIbgpdKD5Ft+1NGUR+bSxdv1o+NEhIHpKwPECMpQ5zKucTIC5MThFt2k4o7U2472eentSNPmPyN6J47eTxfqL8g1TR4ZnICL5cIzipASgsk3/HTaNSWPHJs7sRmGltMTorbp/hkcmZ6LrT+Vqy0RvWKzxeS4aaTUZ9X973DLKOorgBF78tEj6Upqm3u0q1A6ZsBuOygxVLxdqic5rDP51Ay+f+erFR1H42IOZeZKE/RCzmCDnAkaPWeXVhnJklLreSqB0ll+c3mg/47f1Hv1r0DLUhEUpeaJAILFK3R8ZBF12mrlj8QI6WBKJXWYDEsMCvyPgosp23INnWdNIUMTBw=
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      install:
        - if test ! -e $HOME/android-sdk-dl/sdk-tools.zip ; then curl --create-dirs https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -o $HOME/android-sdk-dl/sdk-tools.zip ; fi
        - unzip -qq -n $HOME/android-sdk-dl/sdk-tools.zip -d $ANDROID_HOME
        - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'tools' > /dev/null
        - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platform-tools' > /dev/null
        - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'emulator' > /dev/null
        - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platforms;android-26' > /dev/null
        - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'system-images;android-24;default;armeabi-v7a' > /dev/null
#      before_script:
#        - echo no | $ANDROID_HOME/tools/bin/avdmanager create avd --force -n test  -k 'system-images;android-24;default;armeabi-v7a' > /dev/null
#        - curl https://gist.githubusercontent.com/lionel1704/c696119831cfda3b2c63ce8916ba21ef/raw/7c60e9e10e8abcb275361685d721be986d1be3e6/android-wait-for-emulator > android-wait-for-emulator
#        - $ANDROID_HOME/tools/emulator -avd test -no-window -no-audio &
#        - chmod +x ./android-wait-for-emulator
#        - ./android-wait-for-emulator
#        - $ANDROID_HOME/platform_tools/adb shell input keyevent 82 &
#      before_deploy:
#        - ./gradlew :safe-app-android:javadoc
#      deploy:
#        provider: pages
#        skip-cleanup: true
#        github-token: $GH_ACCESS_TOKEN
#        local_dir: safe-app-android/build/docs/javadoc
#        on:
#          branch: master
#    - os: osx
#      osx_image: xcode10.1
#  allow_failures:
#    - os: osx
before_install:
  - chmod +x gradlew
  - mkdir -p $HOME/.android
  - mkdir -p $ANDROID_HOME/licenses
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
script:
  - chmod +x gradlew
  - ./gradlew download-nativelibs
  - ./gradlew check
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew :safe-app-android:runInstrumentationTests; fi
  - ./gradlew  coveralls
