image:
  - Previous Visual Studio 2015
environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
clone_folder: "C:\\projects\\safe_app_java"
init:
  - cd "C:\projects\safe_app_java"
  - git config --global core.autocrlf true
build: off
test_script:
  - gradlew.bat download-nativelibs
  - gradlew.bat check